[package]
name = "elastic"
version = "0.11.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
keywords = ["elasticsearch", "search"]
description = "A modular client for the Elasticsearch REST API."
documentation = "https://docs.rs/elastic/"
repository = "https://github.com/elastic-rs/elastic"

[features]
nightly = ["elastic_reqwest/nightly"]

[dependencies]
error-chain = "~0.7.0"
serde = "~0.9.0"
serde_json = "~0.9.0"
reqwest = "~0.4.0"

elastic_reqwest = { version = "~0.6.0", git = "https://github.com/elastic-rs/elastic-reqwest.git", branch = "feat/update-requests" }
elastic_requests = { version = "~0.3.0", git = "https://github.com/elastic-rs/elastic-requests.git", branch = "feat/generic-body" }
elastic_responses = "~0.5.0"
elastic_types = "~0.13.0"

[dev-dependencies]
json_str = "^0.*"
serde_derive = "~0.9.0"
elastic_derive = "~0.1.0"