[package]
name = "elastic"
version = "0.12.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
keywords = ["elasticsearch", "search"]
description = "A modular client for the Elasticsearch REST API."
documentation = "https://docs.rs/elastic/"
repository = "https://github.com/elastic-rs/elastic"

[features]
nightly = ["elastic_reqwest/nightly"]

[dependencies]
error-chain = "~0.9.0"
serde = "~1"
serde_json = "~1"
reqwest = "~0.6.0"

elastic_reqwest = "~0.8.0"
elastic_types = "~0.17.1"

[dev-dependencies]
json_str = "^0.*"
serde_derive = "~1"
elastic_derive = { version = "~0.12.0", path = "../derive" }