[package]
name = "elastic_client"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
rotor = "*"
chomp = "*"

[dependencies.elastic_types]
path = "../types"