[package]
name = "elastic_bench"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[profile.release]
debug = true

[dependencies]
serde = "*"
serde_derive = "*"
json_str = { version = "*", features = ["nightly"]}

elastic = { version = "*", path = "../../../elastic", features = "nightly" }

lazy_static = "*"
time = "*"
stopwatch = "*"
