[package]
name = "bulk"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly = ["elastic_reqwest/nightly"]
profiling = []

[dependencies]
elastic_reqwest = { version = "*", path = "../../" }

lazy_static = { version = "*", optional = true }
