[package]
name = "elastic_hyper_samples"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
profiling = []

[dependencies]
elastic_reqwest = { version = "*", path = "../../" }
elastic_requests = "*"

lazy_static = { version = "*", optional = true }
