[package]
name = "bulk"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
json_str = "*"
elastic_reqwest = "*"
elastic_requests = "*"
elastic_responses = { version = "*", path = "../../" }
serde = "~0.9"
serde_derive = "~0.9"
serde_json = "~0.9"