sudo: false
language: rust

matrix:
  include:
    - rust: stable
      env:
        - CHANNEL="stable"
    - rust: nightly
      env:
        - CHANNEL="nightly"

script:
  - |
      cargo test &&
      if [ "$CHANNEL" == "nightly" ]; then cargo bench; fi
