sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

rust:
  - nightly

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo test &&
      cd derive &&
      travis-cargo test &&
      cd ../examples/account_sample &&
      travis-cargo test &&
      cd ../../benches/rust/elastic &&
      travis-cargo --only nightly build &&
      cd ../elastic-raw &&
      travis-cargo --only nightly build &&
      cd ../../../ &&
      travis-cargo doc
after_success:
  - travis-cargo doc-upload