language: rust
os:
  - linux
  - osx
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
script:
  - cd types
  - cargo build -v
  - cargo test -v
  - cargo doc
  - cd ../codegen
  - cargo build -v
  - cargo test -v
  - cargo doc
