language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
  - cd types
  - cargo build -v
  - cargo test -v
  - cargo doc
  - cd ../codegen
  - cargo build -v
  - cargo test -v
  - cargo doc
