[package]
authors = ["Stephan Buys <stephan.buys@panoptix.co.za>"]
name = "elastic_responses"
version = "0.2.1"
license = "MIT/Apache-2.0"
description = "Parses search results from Elasticsearch and presents results using convenient iterators."
documentation = "https://docs.rs/elastic_responses/0.2.1/elastic_responses/"
repository = "https://github.com/stephanbuys/elastic-responses"
exclude = [ "samples" ]

[dependencies]
json_str = "~0.3"
log = "~0.3"
serde = "~0.8"
serde_derive = "~0.8"
serde_json = "~0.8"
slog = "~1.4"
slog-envlogger = "~0.5"
slog-stdlog = "~1.1"
