[package]
name = "elastic_reqwest"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>", "Stephan Buys <stephan.buys@gmail.com>"]
license = "Apache-2.0"
description = "A lightweight implementation of the Elasticsearch API based on reqwest."
documentation = "https://docs.rs/elastic_reqwest/0.1.0/elastic_reqwest/"
repository = "https://github.com/elastic-rs/elastic-hyper"
exclude = [ "samples" ]

[dependencies]
elastic_requests = "~0.1.2"
reqwest = "~0.2.0"
url = "~1"

[dev-dependencies]
json_str = "*"
