[package]
name = "elastic_requests"
version = "0.0.1"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
elastic_codegen = { version = "*", git = "https://github.com/elastic-rs/elastic-codegen" }