[package]
authors = ["Stephan Buys <stephan.buys@panoptix.co.za>"]
name = "elastic_responses"
version = "0.2.0"
license = "MIT/Apache-2.0"
description = "Parses search results from Elasticsearch and presents results using convenient iterators."
documentation = "https://docs.rs/elastic_responses/0.2.0/elastic_responses/"
repository = "https://github.com/stephanbuys/elastic_responses"
exclude = [ "samples" ]

[dependencies]
json_str = "*"
log = "*"
serde = "0.8"
serde_derive = "0.8"
serde_json = "^0.8"
slog = "*"
slog-envlogger = "*"
slog-stdlog = "*"
