[package]
authors = ["Stephan Buys <stephan.buys@panoptix.co.za>"]
name = "elastic_responses"
version = "0.1.0"

[dependencies]
json_str = "*"
log = "*"
serde = "0.8"
serde_derive = "0.8"
serde_json = "^0.8"
slog = "*"
slog-envlogger = "*"
slog-stdlog = "*"
