[package]
authors = ["Stephan Buys <stephan.buys@panoptix.co.za>"]
name = "elastic_responses"
version = "0.5.1"
license = "MIT/Apache-2.0"
description = "Parses search results from Elasticsearch and presents results using convenient iterators."
documentation = "https://docs.rs/elastic_responses"
repository = "https://github.com/elastic-rs/elastic-responses"
exclude = [ "samples" ]

[dependencies]
log = "~0.3"
serde = "~0.9"
serde_derive = "~0.9"
serde_json = "~0.9"
slog = "~1.4"
slog-envlogger = "~0.5"
slog-stdlog = "~1.1"
quick-error = "~1.1"

[dev-dependencies]
json_str = "^0.*"
