[package]
name = "elastic_types_codegen"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[lib]
name = "elastic_types_codegen"
crate_type = ["dylib"]

[dependencies]
chrono = "*"