[package]
name = "elastic_types"
version = "0.1.4"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
default = [
  "boolean_ty",
  "date_ty",
  "geo_ty",
  "number_ty",
  "response_ty",
  "string_ty"
]
no_response_ty = [
  "boolean_ty",
  "date_ty",
  "geo_ty",
  "number_ty",
  "string_ty"
]
boolean_ty = []
date_ty = [ "chrono" ]
geo_ty = [ "geojson" ]
number_ty = []
response_ty = []
string_ty = []

nightly-testing = [ "clippy" ]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
clippy = { version = "*", optional = true }

[dependencies.chrono]
version = "*"
optional = true
features = [ "serde" ]

[dependencies.geojson]
version = "*"
optional = true
features = [ "with-serde" ]

[dependencies.elastic_macros]
version = "*"
path = "../macros"
features = [ "types" ]
