[package]
name = "elastic_types"
version = "0.2.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
description = "A strongly-typed implementation of Elasticsearch core types and Mapping API."
documentation = "http://kodraus.github.io/rustdoc/elastic_types/"
repository = "https://github.com/KodrAus/elasticsearch-rs"
build = "build.rs"

[features]
default = [
  "serde_codegen",
  "elastic_date_macros"
]
nightly = [
  "serde_macros",
  "elastic_date_macros/nightly"
]
nightly-testing = [
  "nightly",
  "clippy",
  "elastic_types_macros"
]

[dependencies]
serde = "~0.7.0"
serde_json = "~0.7.0"
serde_macros = { version = "*", optional = true }
elastic_date_macros = { version = "~0.2.1", optional = true }
chrono = { version = "~0.2.20", features = [ "serde" ] }
geojson = { version = "~0.2.1", features = [ "with-serde" ] }

clippy = { version = "^0.*", optional = true }
elastic_types_macros = { version = "^0.*", path = "../macros/types", optional = true }

[build-dependencies]
serde_codegen = { version = "*", optional = true }
syntex = "*"

[dev-dependencies]
json_str = "^0.*"
