[package]
name = "elastic_types"
version = "0.2.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
description = "A strongly-typed implementation of Elasticsearch core types and Mapping API."
documentation = "http://kodraus.github.io/rustdoc/elastic_types/"
repository = "https://github.com/KodrAus/elasticsearch-rs"
build = "build.rs"

[features]
stable = [
  "serde_codegen"
]
nightly = [
  "serde_macros"
]
default = [
  "stable",
  "date-ty",
  "geo-ty"
]
nightly-default = [
  "nightly",
  "date-ty-nightly",
  "geo-ty-nightly"
]
nightly-testing = [
  "nightly-default",
  "clippy",
  "elastic_types_macros"
]

date-ty = [
  "chrono",
  "elastic_date_macros"
]
date-ty-nightly = [
  "chrono",
  "elastic_date_macros/nightly"
]

geo-ty = [
  "geo",
  "geohash",
  "geojson"
]
geo-ty-nightly = [
  "geo-ty"
]

[dependencies]
serde = "~0.7.0"
serde_json = "~0.7.0"
serde_macros = { version = "*", optional = true }

chrono = { version = "~0.2.20", optional = true, features = [ "serde" ] }
elastic_date_macros = { version = "~0.2.1", optional = true }

geo = { version = "~0.0.7", optional = true }
geohash = { version = "~0.2.6", optional = true }
geojson = { version = "~0.2.1", optional = true, features = [ "with-serde" ] }

clippy = { version = "^0.*", optional = true }
elastic_types_macros = { version = "^0.*", path = "../macros/types", optional = true }

[build-dependencies]
serde_codegen = { version = "*", optional = true }
syntex = "*"

[dev-dependencies]
json_str = "^0.*"
