[package]
name = "elastic_types"
version = "0.1.4"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly-testing = [ "clippy" ]

[dependencies]
chrono = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
clippy = { version = "*", optional = true }

[dependencies.elastic_macros]
version = "*"
path = "../macros"
features = [ "types" ]