[package]
name = "codegen"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
elastic_codegen = { version = "*", git = "https://github.com/elastic-rs/elastic-codegen" }