[package]
name = "elastic_hyper_fltrd_bench"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
hyper = "*"
elastic_hyper = "*"
json_str = "*"
"stopwatch" = "*"
