[package]
name = "elastic_hyper_raw_bench"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
hyper = "*"
elastic_hyper = "*"
elastic_macros = "*"
"stopwatch" = "*"
