[package]
name = "elastic_rotor"
version = "0.0.1"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
url = "*"
rotor = "*"
rotor-http = { version = "*", git = "https://github.com/KodrAus/rotor-http" }
rotor-tools = "*"
lazy_static = "*"
crossbeam = "*"