[package]
name = "elastic_hyper"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
codegen = ["elastic_codegen"]

[dependencies]

[dependencies.elastic_codegen]
path = "../codegen"
optional = true