[package]
name = "elastic_hyper_samples"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly-testing = []

[dependencies]
hyper = "~0.9.0"
elastic_hyper = { version = "*", path = "../../" }
elastic_requests = "*"
elastic_types = { version = "*", features = ["nightly"]}
elastic_types_derive = "*"
json_str = { version = "*", features = ["nightly"]}
serde = "~0.8.0"
serde_derive = "~0.8.0"
serde_json = "~0.8.0"
