[package]
name = "elastic_hyper_samples"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly-testing = []

[dependencies]
elastic_hyper = { version = "*", path = "../../" }
json_str = { version = "*", features = ["nightly"]}
hyper = "~0.9.0"
elastic_types = { version = "*", path = "../../../types", features = ["nightly"]}
elastic_types_macros = { version = "*", path = "../../../macros/types" }
serde = "~0.8.0"
serde_macros = "~0.8.0"
serde_json = "~0.8.0"
