[package]
name = "elastic_hyper_samples"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly-testing = []

[dependencies]
elastic_hyper = "~0.3.0"
json_str = "*"
hyper = "~0.9.0"
