[package]
name = "elastic_types_macros"
version = "0.3.1"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
description = "Compile-time code generation for Elasticsearch type implementations."
documentation = "http://kodraus.github.io/rustdoc/elastic_types_macros/"
repository = "https://github.com/KodrAus/elasticsearch-rs"

[lib]
name = "elastic_types_macros"
crate_type = [ "dylib" ]
plugin = true

[features]
serde-attrs = []
nightly-testing = [ "clippy" ]

[dependencies]
serde = "~0.7.0"
serde_json = "~0.7.0"
serde_codegen_internals = { version = "~0.1.0", default-features = false }
serde_macros = "~0.7.0"
clippy = { version = "^0.*", optional = true }
