[package]
name = "elastic_types_macros"
version = "0.4.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
description = "Compile-time code generation for Elasticsearch type implementations."
documentation = "http://kodraus.github.io/rustdoc/elastic_types_macros/"
repository = "https://github.com/KodrAus/elasticsearch-rs"

[lib]
name = "elastic_types_macros"
crate_type = [ "dylib" ]
plugin = true

[features]
nightly-testing = [ ]

[dependencies]
serde = "~0.8.0"
serde_json = "~0.8.0"
serde_codegen_internals = { version = "~0.4.0", default-features = false }
serde_macros = "~0.8.0"
