[package]
name = "elastic_bench_bulk"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
profile_memory = []

[dependencies]
elastic = { version = "*", path = "../../../elastic", features = ["nightly"] }
string_cache = { version = "*", optional = true }
inlinable_string = { version = "*", features = ["serde"], optional = true }

lazy_static = { version = "*", optional = true }