[package]
name = "rs-es_bench"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
rs-es = { version = "*", default-features = false, features = [ "nightly" ] }
stopwatch = "*"
time = "*"
