[package]
name = "rs-es_bench"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
"rs-es" = { version = "0.3.1", default-features = false, features = [ "nightly" ] }
"stopwatch" = "*"
