[package]
name = "rs-es_bench"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[profile.release]
debug = true

[dependencies]
serde = "*"
serde_derive = "*"

rs-es = { version = "*", default-features = false }

stopwatch = "*"
time = "*"
