[package]
name = "account-sample"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly = [
	"elastic/nightly"
]

[dependencies]
elastic = { version = "*", path = "../../" }
elastic_types_derive = { version = "*", features = ["elastic"]}

quick-error = "*"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

json_str = "*"