[package]
name = "async-sample"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
elastic_requests = "*"
elastic_responses = "*"

serde = "~0.9.0"
serde_json = "~0.9.0"

tokio-core = "*"
tokio-proto = "*"
futures = "*"
futures-cpupool = "*"
memmap = "*"
hyper = { git = "https://github.com/hyperium/hyper.git" }

quick-error = "*"