[package]
name = "elastic_hyper_samples"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly-testing = []

[dependencies]
elastic_hyper = "*"
json_str = { version = "*", features = ["nightly"]}
hyper = "~0.9.0"
elastic_types = { version = "~0.2.1", features = ["nightly"], default-features = false }
elastic_types_macros = "~0.3.1"
serde = "0.7"
serde_macros = "0.7"
serde_json = "0.7"
