[package]
name = "es_benches"
version = "0.1.0"
authors = ["Ashley Mannix <Ashley.Mannix@sunshinecoast.qld.gov.au>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
hyper = "*"
rs-es = "*"
stopwatch = "*"
elastic_types_codegen = { version = "*", path = "../../types_codegen" }